blank_issues_enabled: false
contact_links:
  - name: ⚙️ Feature Request
    url: https://github.com/mrjones2014/codesettings.nvim/discussions
    about: Please create a GitHub Discussion for feature requests
